name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 8,16 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master
        id: v
      - name: Run tests
        run: v test .

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master
        id: v
      - name: Run tests
        run: v test .

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master
        id: v
      - name: Run tests
        run: v test .
